# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RASCL CI

on:
  push:
    branches: [ develop, feature/**, release/**, bug/**, chore/** ]
  pull_request:
    branches: [ develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Set up and install dependencies
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    name: Build RASCL
    steps:
    - run: yarn build

  lint:
    needs: setup
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - run: yarn lint

  jest:
    needs: setup
    runs-on: ubuntu-latest
    name: Jest and upload coverage
    steps:
    - run: yarn jest
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@a1ed4b322b4b38cb846afb5a0ebfa17086917d27
      uses: codecov/codecov-action@v1.5.0
      with:
        # Directory to search for coverage reports.
        directory: ./coverage
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: jest
